const initialState = {
  users: {
    isSingnedIn: false,
    email: "",
    uid: "",
    username: "",
    backpress: [],
    bowpress: [],
    flutterkick: [],
    frontpress: [],
    hiplift: [],
    kneeliftcombo: [],
    kneelift: [],
    kneetochest: [],
    legraise: [],
    legscissors: [],
    mountainclimber: [],
    opencloselegraise: [],
    overheadarmspin: [],
    overheadarmtwist: [],
    overheadbend: [],
    overheadhipshake: [],
    overheadlungetwist: [],
    overheadpress: [],
    overheadsidebend: [],
    overheadsquat: [],
    pendulumbend: [],
    plank: [],
    ringraisecombo: [],
    russiantwist: [],
    seatedforwardpress: [],
    seatedringraise: [],
    shoulderpress: [],
    sidestep: [],
    squat: [],
    standingtwist: [],
    thighpress: [],
    tricepkickback: [],
    wideSquat: [],
  },
};

export default initialState;
